import { EnhancedPerson } from "@/features/D3/utils/getNodePositions";
import { Tables } from "@/types/dbTypes";

// ROOT ************************************************************************
export function getRootConAndIds(
  allConnections: Tables<"connections">[],
  rootId: number,
) {
  const rootDirectConnections = allConnections.filter(
    (c) => c.source_node_id === rootId,
  );
  const directTargetIds = rootDirectConnections.map((c) => c.target_node_id);

  return { rootDirectConnections, directTargetIds };
}

// PARTNERS ********************************************************************
export function getPartnerConIdsNodes(
  allConnections: Tables<"connections">[],
  directTargetIds: number[],
  peopleCopy: EnhancedPerson[],
) {
  // gets partner DIRECT connections where EITHER partner is a target of the root (DOES NOT GET CHILDREN)
  const shownPartnerConnections = allConnections.filter(
    (c) =>
      c.relationship_type === "spouse" ||
      c.relationship_type === "romantic_partner" ||
      (c.relationship_type === "ex_partner" &&
        (directTargetIds.includes(c.source_node_id) ||
          directTargetIds.includes(c.target_node_id))),
  );
  const shownPartnerConnectionIds = shownPartnerConnections.map((c) => c.id);
  const partnerIds = shownPartnerConnections.flatMap((c) => [
    c.target_node_id,
    c.source_node_id,
  ]);
  const partnerNodes = peopleCopy.filter((p) => partnerIds.includes(p.id));

  return {
    shownPartnerConnections,
    partnerIds,
    partnerNodes,
    shownPartnerConnectionIds,
  };
}

// CHILDREN ********************************************************************
export function getChildrenConAndIds(
  partnerNodes: EnhancedPerson[],
  allConnections: Tables<"connections">[],
) {
  const childrenIds = Array.from(
    new Set(partnerNodes.flatMap((p) => p.children_ids)),
  ).map((id) => Number(id));

  const shownChildrenConnections = allConnections.filter((c) => {
    if (c.relationship_details) {
      return childrenIds.includes(c.relationship_details.child);
    }
    return false;
  });
  const shownChildrenConnectionIds = shownChildrenConnections.map((c) => c.id);

  return { childrenIds, shownChildrenConnections, shownChildrenConnectionIds };
}

const FINAL_NODES = [
  {
    children_ids: null,
    created_at: "2024-07-20T14:07:07.332245+00:00",
    date_of_birth: "2000-10-01",
    date_of_death: null,
    first_name: "Shawn",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    hiddenConnections: 0,
    id: 1,
    last_name: "Ballay",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "sh AW n",
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: null,
  },
  {
    children_ids: ["10", "21"],
    created_at: "2024-07-20T14:08:06.754277+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Aaron",
    gift_ideas: ["Baby thing1", "Babything2", "Workout app"],
    group_id: 2,
    group_name: "Best Friends",
    hiddenConnections: 0,
    id: 2,
    last_name: "Mackenzie",
    maiden_name: null,
    partner_details: [[Object], [Object]],
    partner_id: 9,
    partner_type: "spouse",
    phonetic_name: "Ah run",
    preferred_name: "Amac",
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:12:10.751453+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Donnie",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    hiddenConnections: 0,
    id: 3,
    last_name: "Irons",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "dah nee",
    preferred_name: "Don",
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:13:11.728096+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Steve",
    gift_ideas: ["Bachstuff1", "Bachstuff2"],
    group_id: 2,
    group_name: "Best Friends",
    hiddenConnections: 0,
    id: 4,
    last_name: "Smith",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "st EE v",
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:13:40.640285+00:00",
    date_of_birth: "1987-06-01",
    date_of_death: "2022-01-01",
    first_name: "Nolast",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    hiddenConnections: 0,
    id: 5,
    last_name: null,
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:16:38.501838+00:00",
    date_of_birth: "1992-02-15",
    date_of_death: "2024-07-01",
    first_name: "Bob",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    hiddenConnections: 0,
    id: 6,
    last_name: "Johnson",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "b ah b",
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:17:51.921577+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Drake",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    hiddenConnections: 0,
    id: 7,
    last_name: "Davis",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "dr AI k",
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:18:29.73753+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Michelle",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    hiddenConnections: 0,
    id: 8,
    last_name: null,
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: "m ih - sh EH l",
    preferred_name: null,
    sex: "female",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T19:13:48.184445+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Ashley",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    hiddenConnections: 0,
    id: 17,
    last_name: "Cranfield",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T19:14:07.652311+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Jeff",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    hiddenConnections: 0,
    id: 18,
    last_name: "Cranfield",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T19:35:40.425788+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Cody",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    hiddenConnections: 0,
    id: 19,
    last_name: "Zwier",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: "Code",
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T19:13:06.095934+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "John",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    hiddenConnections: 0,
    id: 16,
    last_name: "Cheramie",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["1"],
  },
  {
    children_ids: null,
    created_at: "2024-07-20T14:25:12.091096+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Levi",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    hiddenConnections: 0,
    id: 10,
    last_name: "Mackenzie",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["2", "9"],
  },
  {
    children_ids: null,
    created_at: "2024-08-05T23:05:26.466483+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "2ndChild",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    hiddenConnections: 0,
    id: 21,
    last_name: "Aarons2nd",
    maiden_name: null,
    partner_details: null,
    partner_id: null,
    partner_type: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shownConnections: 0,
    source_node_ids: ["2", "20"],
  },
  {
    children_ids: ["10"],
    created_at: "2024-07-20T14:24:47.404169+00:00",
    date_of_birth: null,
    date_of_death: null,
    first_name: "Rachel",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    hiddenConnections: 0,
    id: 9,
    last_name: "Mackenzie",
    maiden_name: null,
    partner_details: [[Object]],
    partner_id: 2,
    partner_type: "spouse",
    phonetic_name: null,
    preferred_name: "Rach",
    sex: "female",
    shownConnections: 0,
    source_node_ids: ["2"],
  },
];

const FINAL_CONNS = [
  {
    created_at: "2024-07-20T14:09:26.741696+00:00",
    id: 1,
    relationship_details: null,
    relationship_type: "friend",
    source_node_id: 1,
    target_node_id: 2,
  },
  {
    created_at: "2024-07-20T14:20:22.55563+00:00",
    id: 2,
    relationship_details: null,
    relationship_type: "friend",
    source_node_id: 1,
    target_node_id: 3,
  },
];

// For each node id (key), gives an array of all direct connections of that node where that node is the source
const CONN_OBJ = {
  "1": {
    directConns: [
      {
        id: 1,
        created_at: "2024-07-20T14:09:26.741696+00:00",
        source_node_id: 1,
        target_node_id: 2,
        relationship_type: "friend",
        relationship_details: null,
      },
      {
        id: 2,
        created_at: "2024-07-20T14:20:22.55563+00:00",
        source_node_id: 1,
        target_node_id: 3,
        relationship_type: "friend",
        relationship_details: null,
      },
      {
        id: 3,
        created_at: "2024-07-20T14:20:36.040121+00:00",
        source_node_id: 1,
        target_node_id: 4,
        relationship_type: "friend",
        relationship_details: null,
      },
      {
        id: 4,
        created_at: "2024-07-20T14:21:02.655177+00:00",
        source_node_id: 1,
        target_node_id: 5,
        relationship_type: "friend",
        relationship_details: null,
      },
      {
        id: 5,
        created_at: "2024-07-20T14:21:24.155532+00:00",
        source_node_id: 1,
        target_node_id: 6,
        relationship_type: "sibling",
        relationship_details: null,
      },
      {
        id: 6,
        created_at: "2024-07-20T14:21:53.545954+00:00",
        source_node_id: 1,
        target_node_id: 7,
        relationship_type: "coworker",
        relationship_details: null,
      },
      {
        id: 7,
        created_at: "2024-07-20T14:22:12.272541+00:00",
        source_node_id: 1,
        target_node_id: 8,
        relationship_type: "coworker",
        relationship_details: null,
      },
      {
        id: 32,
        created_at: "2024-07-20T19:15:06.726173+00:00",
        source_node_id: 1,
        target_node_id: 17,
        relationship_type: "coworker",
        relationship_details: null,
      },
      {
        id: 34,
        created_at: "2024-07-20T19:15:50.777921+00:00",
        source_node_id: 1,
        target_node_id: 18,
        relationship_type: "coworker",
        relationship_details: null,
      },
      {
        id: 35,
        created_at: "2024-07-20T19:36:25.528396+00:00",
        source_node_id: 1,
        target_node_id: 19,
        relationship_type: "friend",
        relationship_details: null,
      },
      {
        id: 33,
        created_at: "2024-07-20T19:15:29.675303+00:00",
        source_node_id: 1,
        target_node_id: 16,
        relationship_type: "coworker",
        relationship_details: null,
      },
    ],
    currentPartnerId: null,
    bioChildrenNodeIds: [],
  },
  "2": {
    directConns: [
      {
        id: 8,
        created_at: "2024-07-20T14:27:54.515567+00:00",
        source_node_id: 2,
        target_node_id: 9,
        relationship_type: "spouse",
        relationship_details: null,
      },
      {
        id: 9,
        created_at: "2024-07-20T14:29:05.076905+00:00",
        source_node_id: 2,
        target_node_id: 10,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 10, parent: 2 },
      },
      {
        id: 15,
        created_at: "2024-07-20T14:35:17.465332+00:00",
        source_node_id: 2,
        target_node_id: 14,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 2, parent: 14 },
      },
      {
        id: 16,
        created_at: "2024-07-20T14:35:29.28415+00:00",
        source_node_id: 2,
        target_node_id: 15,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 2, parent: 15 },
      },
      {
        id: 37,
        created_at: "2024-08-05T23:08:02.359857+00:00",
        source_node_id: 2,
        target_node_id: 21,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 21, parent: 2 },
      },
      {
        id: 40,
        created_at: "2024-08-05T23:11:07.777623+00:00",
        source_node_id: 2,
        target_node_id: 20,
        relationship_type: "ex_partner",
        relationship_details: null,
      },
    ],
    currentPartnerId: 9,
    bioChildrenNodeIds: [10, 21],
  },
  "9": {
    directConns: [
      {
        id: 10,
        created_at: "2024-07-20T14:29:26.66729+00:00",
        source_node_id: 9,
        target_node_id: 10,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 10, parent: 9 },
      },
    ],
    currentPartnerId: 2,
    bioChildrenNodeIds: [10],
  },
  "11": {
    directConns: [
      {
        id: 12,
        created_at: "2024-07-20T14:32:56.744166+00:00",
        source_node_id: 11,
        target_node_id: 12,
        relationship_type: "spouse",
        relationship_details: null,
      },
      {
        id: 13,
        created_at: "2024-07-20T14:33:21.969605+00:00",
        source_node_id: 11,
        target_node_id: 13,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 13, parent: 11 },
      },
      {
        id: 17,
        created_at: "2024-07-20T14:35:41.714255+00:00",
        source_node_id: 11,
        target_node_id: 14,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 11, parent: 14 },
      },
      {
        id: 18,
        created_at: "2024-07-20T14:35:52.933909+00:00",
        source_node_id: 11,
        target_node_id: 15,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 11, parent: 15 },
      },
    ],
    currentPartnerId: 12,
    bioChildrenNodeIds: [13],
  },
  "12": {
    directConns: [
      {
        id: 14,
        created_at: "2024-07-20T14:33:35.881146+00:00",
        source_node_id: 12,
        target_node_id: 13,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 13, parent: 12 },
      },
    ],
    currentPartnerId: 11,
    bioChildrenNodeIds: [13],
  },
  "15": {
    directConns: [
      {
        id: 36,
        created_at: "2024-07-24T22:14:14.394002+00:00",
        source_node_id: 15,
        target_node_id: 14,
        relationship_type: "spouse",
        relationship_details: null,
      },
    ],
    currentPartnerId: 14,
    bioChildrenNodeIds: [2, 11],
  },
  "20": {
    directConns: [
      {
        id: 38,
        created_at: "2024-08-05T23:08:51.597329+00:00",
        source_node_id: 20,
        target_node_id: 21,
        relationship_type: "parent_child_biological",
        relationship_details: { child: 21, parent: 20 },
      },
    ],
    currentPartnerId: null,
    bioChildrenNodeIds: [],
  },
};

const CONNS_TO_ADD = [
  {
    created_at: "2024-07-20T14:29:05.076905+00:00",
    id: 9,
    relationship_details: { child: 10, parent: 2 },
    relationship_type: "parent_child_biological",
    source_node_id: 2,
    target_node_id: 10,
  },
  {
    created_at: "2024-08-05T23:08:02.359857+00:00",
    id: 37,
    relationship_details: { child: 21, parent: 2 },
    relationship_type: "parent_child_biological",
    source_node_id: 2,
    target_node_id: 21,
  },
  {
    created_at: "2024-07-20T14:27:54.515567+00:00",
    id: 8,
    relationship_details: null,
    relationship_type: "spouse",
    source_node_id: 2,
    target_node_id: 9,
  },
];
