import { Tables } from "@/types/dbTypes";

export interface NodeHashObj extends Tables<"people"> {
  isShown: boolean;
  x: number;
  y: number;
}

// allPeople will have the rootNode where is_current_root === true
export function getInitialNodes(
  allPeople: Tables<"people">[],
  allConnections: Tables<"connections">[],
): {
  nodeHash: { [nodeId: number]: NodeHashObj };
  finalConnections: Tables<"connections">[];
} {
  let nodeHash: {
    [nodeId: number]: NodeHashObj;
  } = {};

  let defaultDepth = 2;

  // initialize the hashObj
  allPeople.forEach((person) => {
    if (nodeHash[person.id]) return;

    nodeHash[person.id] = {
      isShown: false,
      x: 0,
      y: 0,
      ...person,
    };
  });

  function setUserConnectedNodes(): void {
    allPeople.forEach((p) => {
      if (p.depth_from_user <= defaultDepth) {
        nodeHash[p.id].isShown = true;
      } else {
        nodeHash[p.id].isShown = false;
      }
    });
  }

  setUserConnectedNodes();

  return {
    nodeHash,
    finalConnections: [],
  };
}

const hash = {
  "1": {
    children_details: null,
    created_at: "2024-07-20T14:07:07.332245+00:00",
    date_of_birth: "2000-10-01",
    date_of_death: null,
    depth_from_user: 0,
    first_name: "Shawn",
    fx: 196.5,
    fy: 773,
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 1,
    isShown: true,
    is_current_root: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: "sh AW n",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: null,
    x: 0,
    y: 0,
  },
  "10": {
    children_details: null,
    created_at: "2024-07-20T14:25:12.091096+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Levi",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 10,
    isShown: true,
    is_current_root: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "11": {
    children_details: [[Object]],
    created_at: "2024-07-20T14:25:46.090227+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Lauren",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 11,
    isShown: false,
    is_current_root: false,
    last_name: "Something",
    maiden_name: "Mackenzie",
    parent_details: [[Object], [Object]],
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "12": {
    children_details: [[Object]],
    created_at: "2024-07-20T14:26:16.95771+00:00",
    date_of_birth: "1986-11-01",
    date_of_death: null,
    depth_from_user: 4,
    first_name: "Eric",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 12,
    isShown: false,
    is_current_root: false,
    last_name: "Something",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "13": {
    children_details: null,
    created_at: "2024-07-20T14:26:48.225131+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 4,
    first_name: "Mackenzie",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 13,
    isShown: false,
    is_current_root: false,
    last_name: "Something",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "14": {
    children_details: [[Object], [Object]],
    created_at: "2024-07-20T14:34:08.695662+00:00",
    date_of_birth: "1995-12-01",
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Joe",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 14,
    isShown: false,
    is_current_root: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "15": {
    children_details: [[Object], [Object]],
    created_at: "2024-07-20T14:34:27.214013+00:00",
    date_of_birth: "1989-06-01",
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Carmen",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 15,
    isShown: false,
    is_current_root: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "16": {
    children_details: null,
    created_at: "2024-07-20T19:13:06.095934+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "John",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 16,
    isShown: true,
    is_current_root: false,
    last_name: "Cheramie",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "17": {
    children_details: null,
    created_at: "2024-07-20T19:13:48.184445+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Ashley",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 17,
    isShown: true,
    is_current_root: false,
    last_name: "Cranfield",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "18": {
    children_details: null,
    created_at: "2024-07-20T19:14:07.652311+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Jeff",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 18,
    isShown: true,
    is_current_root: false,
    last_name: "Cranfield",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "19": {
    children_details: null,
    created_at: "2024-07-20T19:35:40.425788+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Cody",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    id: 19,
    isShown: true,
    is_current_root: false,
    last_name: "Zwier",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: "Code",
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "2": {
    children_details: [[Object]],
    created_at: "2024-07-20T14:08:06.754277+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Aaron",
    gift_ideas: ["Baby thing1", "Babything2", "Workout app"],
    group_id: 2,
    group_name: "Best Friends",
    id: 2,
    isShown: true,
    is_current_root: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: [[Object], [Object]],
    phonetic_name: "Ah run",
    preferred_name: "Amac",
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "20": {
    children_details: [[Object]],
    created_at: "2024-08-05T23:03:37.796964+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Gina",
    gift_ideas: null,
    group_id: 3,
    group_name: null,
    id: 20,
    isShown: false,
    is_current_root: false,
    last_name: "AaronEx",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "21": {
    children_details: null,
    created_at: "2024-08-05T23:05:26.466483+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Aarons2ndChild",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 21,
    isShown: true,
    is_current_root: false,
    last_name: "Aarons2nd",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
  "23": {
    children_details: [[Object], [Object], [Object]],
    created_at: "2024-08-08T18:08:26.59391+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Carol",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 23,
    isShown: true,
    is_current_root: false,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "24": {
    children_details: [[Object], [Object], [Object]],
    created_at: "2024-08-08T18:09:18.182221+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Fred",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 24,
    isShown: true,
    is_current_root: false,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "25": {
    children_details: null,
    created_at: "2024-08-08T18:09:54.377834+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Kyle",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 25,
    isShown: true,
    is_current_root: false,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "26": {
    children_details: null,
    created_at: "2024-08-08T18:10:18.994418+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Tara",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 26,
    isShown: true,
    is_current_root: false,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "3": {
    children_details: null,
    created_at: "2024-07-20T14:12:10.751453+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Donnie",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    id: 3,
    isShown: true,
    is_current_root: false,
    last_name: "Irons",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "dah nee",
    preferred_name: "Don",
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "4": {
    children_details: null,
    created_at: "2024-07-20T14:13:11.728096+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Steve",
    gift_ideas: ["Bachstuff1", "Bachstuff2"],
    group_id: 2,
    group_name: "Best Friends",
    id: 4,
    isShown: true,
    is_current_root: false,
    last_name: "Smith",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "st EE v",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "5": {
    children_details: null,
    created_at: "2024-07-20T14:13:40.640285+00:00",
    date_of_birth: "1987-06-01",
    date_of_death: "2022-01-01",
    depth_from_user: 1,
    first_name: "Nolast",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    id: 5,
    isShown: true,
    is_current_root: false,
    last_name: null,
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "6": {
    children_details: null,
    created_at: "2024-07-20T14:16:38.501838+00:00",
    date_of_birth: "1992-02-15",
    date_of_death: "2024-07-01",
    depth_from_user: 1,
    first_name: "Bob",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    id: 6,
    isShown: true,
    is_current_root: false,
    last_name: "Johnson",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "b ah b",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "7": {
    children_details: null,
    created_at: "2024-07-20T14:17:51.921577+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Drake",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 7,
    isShown: true,
    is_current_root: false,
    last_name: "Davis",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "dr AI k",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "8": {
    children_details: null,
    created_at: "2024-07-20T14:18:29.73753+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Michelle",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 8,
    isShown: true,
    is_current_root: false,
    last_name: null,
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "m ih - sh EH l",
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    x: 0,
    y: 0,
  },
  "9": {
    children_details: [[Object]],
    created_at: "2024-07-20T14:24:47.404169+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Rachel",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 9,
    isShown: true,
    is_current_root: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: "Rach",
    sex: "female",
    shallowest_ancestor: 2,
    x: 0,
    y: 0,
  },
};
