import { createSlice, PayloadAction } from "@reduxjs/toolkit";

import { PositionedLink, PositionedNode } from "@/features/D3/types/d3Types";
import { Child, Parent, Partner } from "@/types/dbTypes";

export interface INode2 {
  id: number;
  created_at: string;
  first_name: string;
  sex: string;

  group_id: number | null;
  group_name: string | null;
  last_name: string | null;
  maiden_name: string | null;
  preferred_name: string | null;
  phonetic_name: string | null;

  date_of_birth: string | null;
  date_of_death: string | null;
  gift_ideas: string[] | null;

  partner_details: Partner[] | null;
  parent_details: Parent[] | null;
  children_details: Child[] | null;

  depth_from_user: number;
  shallowest_ancestor: number;

  isShown: boolean;
  xPosition: number;
  yPosition: number;
}

// !TODO: Current issue is that you're calculating shown/hidden connections at run time, thus you had to alter the interfaces to make it work (not ideal)
export interface TempTillDbFix
  extends Omit<INode2, "shownConnections" | "hiddenConnections"> {}

interface ManageGraphState {
  activeRootNode: INode2 | null;
  activeRootType: "user" | "notUser";

  userNodes: PositionedNode[];
  userLinks: PositionedLink[];

  inspectedNodes: PositionedNode[];
  inspectedLinks: PositionedLink[];
}

const initialState: ManageGraphState = {
  activeRootNode: null,
  activeRootType: "user",

  userNodes: [],
  userLinks: [],

  inspectedNodes: [],
  inspectedLinks: [],
};

const ManageGraphSlice = createSlice({
  name: "manageGraph",
  initialState,
  reducers: {
    // ROOT
    setActiveRootNode: (state, action: PayloadAction<TempTillDbFix>) => {
      state.activeRootNode = {
        ...action.payload,
      };
    },

    // USER (Will not change often)
    setUserNodes: (state, action: PayloadAction<PositionedNode[]>) => {
      state.userNodes = action.payload;
    },
    setUserLinks: (state, action: PayloadAction<PositionedLink[]>) => {
      state.userLinks = action.payload;
    },

    // Changes when user "inspects"
    setInspectedNodes: (state, action: PayloadAction<PositionedNode[]>) => {
      state.inspectedNodes = action.payload;
    },
    setInspectedLinks: (state, action: PayloadAction<PositionedLink[]>) => {
      state.userLinks = action.payload;
    },
  },
});

export const {
  setActiveRootNode,
  setUserNodes,
  setUserLinks,
  setInspectedNodes,
  setInspectedLinks,
} = ManageGraphSlice.actions;

export default ManageGraphSlice.reducer;

const testFormat = [
  {
    children_details: null,
    created_at: "2024-07-20T14:07:07.332245+00:00",
    date_of_birth: "2000-10-01",
    date_of_death: null,
    depth_from_user: 0,
    first_name: "Shawn",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 1,
    isShown: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: "sh AW n",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: null,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object]],
    created_at: "2024-07-20T14:08:06.754277+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Aaron",
    gift_ideas: ["Baby thing1", "Babything2", "Workout app"],
    group_id: 2,
    group_name: "Best Friends",
    id: 2,
    isShown: true,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: [[Object], [Object]],
    phonetic_name: "Ah run",
    preferred_name: "Amac",
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:12:10.751453+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Donnie",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    id: 3,
    isShown: true,
    last_name: "Irons",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "dah nee",
    preferred_name: "Don",
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:13:11.728096+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Steve",
    gift_ideas: ["Bachstuff1", "Bachstuff2"],
    group_id: 2,
    group_name: "Best Friends",
    id: 4,
    isShown: true,
    last_name: "Smith",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "st EE v",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:13:40.640285+00:00",
    date_of_birth: "1987-06-01",
    date_of_death: "2022-01-01",
    depth_from_user: 1,
    first_name: "Nolast",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    id: 5,
    isShown: true,
    last_name: null,
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:16:38.501838+00:00",
    date_of_birth: "1992-02-15",
    date_of_death: "2024-07-01",
    depth_from_user: 1,
    first_name: "Bob",
    gift_ideas: null,
    group_id: 1,
    group_name: "Friends",
    id: 6,
    isShown: true,
    last_name: "Johnson",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "b ah b",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:17:51.921577+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Drake",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 7,
    isShown: true,
    last_name: "Davis",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "dr AI k",
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:18:29.73753+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Michelle",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 8,
    isShown: true,
    last_name: null,
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: "m ih - sh EH l",
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object]],
    created_at: "2024-07-20T14:24:47.404169+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Rachel",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 9,
    isShown: true,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: "Rach",
    sex: "female",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:25:12.091096+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Levi",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 10,
    isShown: true,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object]],
    created_at: "2024-07-20T14:25:46.090227+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Lauren",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 11,
    isShown: false,
    last_name: "Something",
    maiden_name: "Mackenzie",
    parent_details: [[Object], [Object]],
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object]],
    created_at: "2024-07-20T14:26:16.95771+00:00",
    date_of_birth: "1986-11-01",
    date_of_death: null,
    depth_from_user: 4,
    first_name: "Eric",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 12,
    isShown: false,
    last_name: "Something",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T14:26:48.225131+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 4,
    first_name: "Mackenzie",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 13,
    isShown: false,
    last_name: "Something",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object], [Object]],
    created_at: "2024-07-20T14:34:08.695662+00:00",
    date_of_birth: "1995-12-01",
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Joe",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 14,
    isShown: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object], [Object]],
    created_at: "2024-07-20T14:34:27.214013+00:00",
    date_of_birth: "1989-06-01",
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Carmen",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 15,
    isShown: false,
    last_name: "Mackenzie",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T19:13:06.095934+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "John",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 16,
    isShown: true,
    last_name: "Cheramie",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T19:13:48.184445+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Ashley",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 17,
    isShown: true,
    last_name: "Cranfield",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T19:14:07.652311+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Jeff",
    gift_ideas: null,
    group_id: 3,
    group_name: "Coworkers",
    id: 18,
    isShown: true,
    last_name: "Cranfield",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-07-20T19:35:40.425788+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Cody",
    gift_ideas: null,
    group_id: 2,
    group_name: "Best Friends",
    id: 19,
    isShown: true,
    last_name: "Zwier",
    maiden_name: null,
    parent_details: null,
    partner_details: null,
    phonetic_name: null,
    preferred_name: "Code",
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object]],
    created_at: "2024-08-05T23:03:37.796964+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 3,
    first_name: "Gina",
    gift_ideas: null,
    group_id: 3,
    group_name: null,
    id: 20,
    isShown: false,
    last_name: "AaronEx",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-08-05T23:05:26.466483+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Aarons2ndChild",
    gift_ideas: null,
    group_id: null,
    group_name: null,
    id: 21,
    isShown: true,
    last_name: "Aarons2nd",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 2,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object], [Object], [Object]],
    created_at: "2024-08-08T18:08:26.59391+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Carol",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 23,
    isShown: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: [[Object], [Object], [Object]],
    created_at: "2024-08-08T18:09:18.182221+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 1,
    first_name: "Fred",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 24,
    isShown: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: null,
    partner_details: [[Object]],
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-08-08T18:09:54.377834+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Kyle",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 25,
    isShown: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "male",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
  {
    children_details: null,
    created_at: "2024-08-08T18:10:18.994418+00:00",
    date_of_birth: null,
    date_of_death: null,
    depth_from_user: 2,
    first_name: "Tara",
    gift_ideas: null,
    group_id: 4,
    group_name: "Family",
    id: 26,
    isShown: true,
    last_name: "Ballay",
    maiden_name: null,
    parent_details: [[Object], [Object]],
    partner_details: null,
    phonetic_name: null,
    preferred_name: null,
    sex: "female",
    shallowest_ancestor: 1,
    xPosition: 0,
    yPosition: 0,
  },
];
